### ISSUE TITLE
example_08.sdoc throws errors with export

### ISSUE THREAD

**Issue by sebastian-bergt** [strictdoc-project/strictdoc-examples#4]
Hi,
I am trying to follow the readme to run the project with strictdoc version 0.0.58.
But it fails. Could you please help me fix it @stanislaw ?
```
strictdoc-examples$ strictdoc export .
TextXSyntaxError: /home/redacted/prog/strictdoc_example/strictdoc-examples/examples/example_08.sdoc:6:6: Expected ' ' => '-001 REFS:* - TYPE: F'
Reading SDOC: example_01.sdoc ............................... 0.00s
Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.10/site-packages/textx/model.py", line 328, in _parse
    return self.parser_model.parse(self)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 954, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 494, in _parse
    result = p(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 907, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 460, in _parse
    result = [self.nodes[0].parse(parser)]
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 907, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 494, in _parse
    result = p(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 432, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 418, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 907, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 418, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 300, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 379, in _parse
    result = e.parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 798, in parse
    result = self._parse(parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 907, in _parse
    parser._nm_raise(self, c_pos, parser)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1727, in _nm_raise
    raise self.nm
arpeggio.NoMatch: Expected ' ' at position /home/redacted/prog/strictdoc_example/strictdoc-examples/examples/example_08.sdoc:(6, 6) => '-001 REFS:* - TYPE: F'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redacted/.local/lib/python3.10/site-packages/strictdoc/backend/sdoc/reader.py", line 73, in read_from_file
    sdoc, parse_context = self.read_with_parse_context(
  File "/home/redacted/.local/lib/python3.10/site-packages/strictdoc/backend/sdoc/reader.py", line 54, in read_with_parse_context
    document, parse_context = SDReader._read(input_string, file_path)
  File "/home/redacted/.local/lib/python3.10/site-packages/strictdoc/backend/sdoc/reader.py", line 37, in _read
    document: SDocDocument = SDReader.meta_model.model_from_str(
  File "/home/redacted/.local/lib/python3.10/site-packages/textx/metamodel.py", line 646, in model_from_str
    model = self.internal_model_from_file(
  File "/home/redacted/.local/lib/python3.10/site-packages/textx/metamodel.py", line 706, in internal_model_from_file
    model = self._parser_blueprint.clone().get_model_from_str(
  File "/home/redacted/.local/lib/python3.10/site-packages/textx/model.py", line 371, in get_model_from_str
    self.parse(model_str, file_name=file_name)
  File "/home/redacted/.local/lib/python3.10/site-packages/arpeggio/__init__.py", line 1525, in parse
    self.parse_tree = self._parse()
  File "/home/redacted/.local/lib/python3.10/site-packages/textx/model.py", line 331, in _parse
    raise TextXSyntaxError(message=e.message,
textx.exceptions.TextXSyntaxError: /home/redacted/prog/strictdoc_example/strictdoc-examples/examples/example_08.sdoc:6:6: Expected ' ' => '-001 REFS:* - TYPE: F'
error: Parallelizer: One of the child processes has exited prematurely.
```

**Comment by stanislaw** [comment]
Thanks for reporting this. The code became outdated due to the recent migration from REFS to RELATIONS. It should work now on the latest main branch.
